apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastgpt
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: fastgpt
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: fastgpt
  template:
    metadata:
      labels:
        app: fastgpt
    spec:
      containers:
        - name: fastgpt
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: DEFAULT_ROOT_PSW
              value: "Z54ud4kG1azXApuN"
            - name: AIPROXY_API_ENDPOINT
              value: {{ include "fastgpt.aiproxyURI" . }}
            - name: AIPROXY_API_TOKEN
              value: "aiproxy"
            - name: DB_MAX_LINK
              value: "30"
            - name: TOKEN_KEY
              value: "any"
            - name: ROOT_KEY
              value: "root_key"
            - name: FILE_TOKEN_KEY
              value: "filetoken"
            - name: MONGODB_URI
              value: {{ include "fastgpt.mongoURI" . }}
            - name: PG_URL
              value: {{ include "fastgpt.pgvectorURI" . }}
            - name: REDIS_URL
              value: {{ include "fastgpt.redisURI" . }}
            - name: SANDBOX_URL
              value: {{ include "fastgpt.sandboxURI" . }}
            - name: LOG_LEVEL
              value: "debug"
            - name: STORE_LOG_LEVEL
              value: "warn"
            - name: PRO_URL
              value: {{ include "fastgpt.fastgptProURI" . }}
            - name: FE_DOMAIN
              value: ""
            - name: WORKFLOW_MAX_RUN_TIMES
              value: "1000"
            - name: WORKFLOW_MAX_LOOP_TIMES
              value: "100"
            - name: ALLOWED_ORIGINS
              value: ""
            - name: USE_IP_LIMIT
              value: "false"
            - name: CHAT_FILE_EXPIRE_TIME
              value: "7"
          volumeMounts:
            - name: config
              mountPath: /app/data
              readOnly: true
          livenessProbe:
            httpGet:
              path: /api/status
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configmap.name }}